[package]
name = "ms-pdb-linkgen"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
goblin = { version = "0.10.4", default-features = false, features = [
    "std",
    "pe32",
    "pe64",
] }
thiserror = "2.0.17"
